apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets.yaml
  - deployment.yaml
  - service.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 72.6.2
    releaseName: prometheus-stack
    namespace: monitoring
    valuesFile: helm-values.yaml
    includeCRDs: true

replacements:
  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.VAULT_ID
    targets:
      - select:
          group: secrets-store.csi.x-k8s.io
          version: v1
          kind: SecretProviderClass
          name: monitoring-secret-bundle
        fieldPaths:
          - spec.parameters.vaultId