apiVersion: v1
kind: Service
metadata:
  name: monitoring-pushgateway
  namespace: monitoring
spec:
  selector:
    app: monitoring-pushgateway
  ports:
    - name: http
      port: 9091
      targetPort: 9091
