apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - rolebinding.yaml

helmCharts:
  - name: argo-workflows
    repo: https://argoproj.github.io/argo-helm
    version: 0.47.1
    releaseName: argo
    namespace: argo
    valuesFile: helm-values.yaml
