apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - job-init-mlflow.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.VAULT_ID
    targets:
      - select:
          group: secrets-store.csi.x-k8s.io
          version: v1
          kind: SecretProviderClass
          name: postgres-secret-bundle
        fieldPaths:
          - spec.parameters.vaultId